### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by sklizzy** [pirxpilot/liftie#34]
I install the lifitie code and yarn but once hitting make ran into this:

**Comment by sklizzy** [comment]
./node_modules/.bin/jshint app.js bin/generate lib test
make: ./node_modules/.bin/jshint: Command not found
make: *** [Makefile:39: lint] Error 127

**Comment by sklizzy** [comment]
is it a incorrect path for the lint?

**Comment by pirxpilot** [comment]
The path is correct. Make sure to actually run: `yarn` before running `make` though. `yarn` will install the tools in the `node_modules` directory.
