### ISSUE TITLE
Wildcat and Attitash (same owner and site design) data not coming in

### ISSUE THREAD

**Issue by svenjr** [pirxpilot/liftie#35]
Both sites are not showing data
- https://www.attitash.com/the-mountain/mountain-conditions/lift-and-terrain-status.aspx
- https://www.skiwildcat.com/the-mountain/mountain-conditions/lift-and-terrain-status.aspx?difficulty=green%2Cblue%2Cblack

But there is not data coming into Liftie. I think their site design changed

**Comment by pirxpilot** [comment]
Thanks. Should be fixed now. Pretty soon everything will be owned by Vail ;-)

**Comment by svenjr** [comment]
I know! Aggregation theory at work
