### ISSUE TITLE
Sugarloaf website vs liftie status discrepancies 

### ISSUE THREAD

**Issue by geoff5802** [pirxpilot/liftie#37]
When Sugarloaf's website indicates a lift status as hold, it's being returned as 'open' through liftie. If I can figure out why, I'll put together a PR.
- https://www.sugarloaf.com/conditions-and-cams
- https://liftie.info/resort/sugarloaf

**Comment by geoff5802** [comment]
When inspecting the Sugarloaf website, it seems the `hold` indicators use the alt text 'Open' as demonstrated in the screen capture. If I'm understanding how the scraper captures data, it would seem this alt text is likely what is causing the reported discrepancy.
![Screen Shot 2021-02-22 at 2 42 26 PM](https://user-images.githubusercontent.com/15982329/108761784-4827c780-751d-11eb-9828-5ffcb5851ef9.png)

**Comment by pirxpilot** [comment]
Yup - it's using `alt` now, but it's fairly simple to change it to use `src` instead. It would need a regex to extract the interesting part of the image URL. Something like:

```js
attribute: 'src',               // change from alt to src
regex: /-(\w+)\.png$/i   // capture part between a hyphen and .png
```

The parser data is in `libtools/boyne.js` and the parser is shared with couple of other Boyne resorts. It would be good to check if they changed it for all of them.

Let me know if you want to give it a try.

**Comment by geoff5802** [comment]
Thanks for taking care of this!
