### ISSUE TITLE
Feedback on how to scrape Mt Seymour

### ISSUE THREAD

**Issue by matthewhall-ca** [pirxpilot/liftie#47]
https://mtseymour.ca/todays-conditions-hours

@pirxpilot would love your feedback on how to setup a scraper for this terrible markup. My current thought is to do the following:

1. Target based on all `table` element
2. Filter out elements by the first `td` value being `LIFTS`
3. Check for "Closed" string or if not, attempt to turn it into a time range, check to see if the current time is between that range

**Comment by pirxpilot** [comment]
I would go with a `selector` that looks like this:

    'tr:contains(LIFTS) ~ tr'

IOW: `tr` siblings of the `tr` element that contains the `"LIFTS"` string.

As for the status, checking for the '"Closed"' string and assuming `'open'` if not found should be OK. In similar cases Liftie never tries to check for the time ranges. It's not like it's impossible to implement (we do have resort coordinates to check for time zones etc.), but if resort publishes the time range it is highly unlikely that they ever update the real time status.

**Comment by matthewhall-ca** [comment]
Ah thank you! Didn't know about `~`
