### ISSUE TITLE
Cannot read properties of undefined (reading 'foreEach')

### ISSUE THREAD

**Issue by JeppePape** [pirxpilot/liftie#57]
Index.js

var debug = require('debug')('liftie:resort:bad-kleinkirchheim');
module.exports = parse;

function parse(data) {
  var liftStatus = {};

  data.lifts.forEach(function(lift) {
    liftStatus[lift.popup.title.trim()] = lift.status;
  });

  debug('bad-kleinkirchheim lift status:', liftStatus);
  return liftStatus;
}

Resort.json

{
  "name": "bad-kleinkichheim",
  "url": {
    "host": "https://winter.intermaps.com",
    "pathname": "/bad_kleinkirchheim/data?lang=en"
  },
  "api": {
    "host": "https://winter.intermaps.com",
    "pathname": "/bad_kleinkirchheim/data?lang=en"
  },
  "tags": [
    "austria"
  ],
  "ll": [
    null
  ]
}

I know that i shouldnt have to put in the api i like this, when it isnt an api link, however i was just testing out if data?lang=en or api might have been the issue.

**Comment by JeppePape** [comment]
As the title suggest. I have about 40-50 ski resorts in the EU connected to the winter.intermaps.com websites. The index methods are completely identical for all of them and they all work with make. However about half of them return this specific error and doesnt pop up on localhost with the information. I simply am not able to understand the specific reason why this is happening, but i am thinking if any of the rate or time limiters could be a factor. 

Also is there any way to change the time from every 60seconds to 5 minutes for example ?

**Comment by pirxpilot** [comment]
You can change the interval [here][1]

```
var interval = 60 * 1000; // once a minute - fetch status if there were requests
```

It should probably be configurable through environment variable. PRs always welcomed ;-)
I can really comment or help on the root issue though. Definitely not without the code that you added and a way to reproduce it.

[1]: https://github.com/pirxpilot/liftie/blob/2846eeb5c5ddd1217ada923b2b147eeeb51e9656/lib/lifts/index.js#L8

**Comment by JeppePape** [comment]
> You can change the interval [here](https://github.com/pirxpilot/liftie/blob/2846eeb5c5ddd1217ada923b2b147eeeb51e9656/lib/lifts/index.js#L8)
> 
> ```
> var interval = 60 * 1000; // once a minute - fetch status if there were requests
> ```
> 
> It should probably be configurable through environment variable. PRs always welcomed ;-) I can really comment or help on the root issue though. Definitely not without the code that you added and a way to reproduce it.

i suppose that PRs are "push requests" ? :) 

But yeah otherwise i havent really added anything special that hasnt been done in all the other ones on the readme. I always saw this error happen here and there. However after letting it sit for a while it seems that even though the error comes up, it now does give info for nearly all of my resorts. So i ma thinking it might be an issue with the data it receives from the resorts in a particular interval that could be corrupt or wrong.

And thanks for the interval location, i didnt seem to be able to find it!

**Comment by JeppePape** [comment]
As a sidenote, does the examples get redownloaded every 30 mins as well or do they only get downloaded on generation ?

The reason i am asking this, is whether Make can be used to actually test if all the websites function correctly using make as a Test that is run every night to confirm, but this would only work if the example html and json files are actually retrieved more than just once ?

**Comment by pirxpilot** [comment]
You need to run:

    bin/fetch <resort>
  
to update example.

**Comment by JeppePape** [comment]
> You need to run:
> 
> ```
> bin/fetch <resort>
> ```
> 
> to update example.

are you able to replicate the issue, if you add the resort to your own running instance ?

**Comment by JeppePape** [comment]
> You need to run:
> 
> ```
> bin/fetch <resort>
> ```
> 
> to update example.

I just made a pull request, hope that it can be used, but i had to revert some changes to the local copy i had and make a fork instead so i could push some of the resorts i made. A lot of the remaining resorts are getting both lifts and pistes and i have made custom changes to the template files, so i didn't want to add all of that without knowing if it was of any interest to the liftie's vision.


As a sidenote, have you ever tried making multiple parse or module exports within one file ?

I am currently trying to make it work (as i am trying to get both lifts and slopes in one list), where both work separately, however it doesn't work, when bundled together.

module.exports = {
  parseStatements: [
{
  selector: '.snow-report-terrain .ab-status-large',
  parse: 
  {
    name: 1,
    status: {
      child: 0,
      attribute: 'class',
      fn: v => v.split('_').pop()
    }
  }
},
{
    selector: 'div.dynamicCodeInsert.sortableModule.snow-report-terrain.no-edit-bar > div > button > div.ab-status_sub > div',
    parse: 
    {
      name: 2,
      status: {
        child: 0,
        attribute: 'class',
        fn: text => {
          if (text.includes("open")) {
            return 'open';
          }
          return 'closed';
        }
      }
    }
  }
]
};
