### ISSUE TITLE
Parse <br> separated texts?

### ISSUE THREAD

**Issue by FezVrasta** [pirxpilot/liftie#76]
I wanted to add a resort that displays the lifts status as plain text separated by breaking lines...

https://www.terminillo.eu/mappa-impianti-piste-da-sci/

Ideas on how to do it? Can I select text nodes or only HTML nodes are supported?

**Comment by pirxpilot** [comment]
Not sure about directly addressing a text node - check out [fb55/css-select](https://github.com/fb55/css-select) docs.
There is currently no example of that in liftie but `parse` can be a function - it takes `node` and returns `{ name, status }` object (it can also return a falsy value if you want to filter something out. So I would probably try to come up with a selector that gives me all the texts and then ignore empty lines.
I would start with something like `elementor-size-medium > *` and checked if I can find something useful among the nodes and their siblings...
