### ISSUE TITLE
boyne update

### ISSUE THREAD

**Issue by kirby-mp** [pirxpilot/liftie#80]
Tried to make a PR for this but was denied.
Anyways the fix for the Boyne resorts is below.
Tested on local instance and [brighton, big-sky, loon, sugarloaf, sunday-river] are all 
working. 

`module.exports = {
  selector: 'div.liftStatus-lift-icon',
  parse: {
    name: '+/0',
    status: {
      child: '0',
      attribute: 'alt'
    }
  }
};
`

**Comment by pirxpilot** [comment]
Thanks. It's released now.
What do you mean by:

> Tried to make a PR for this but was denied.

In any case: I am totally cool with people sending me references to any git repo - does not have to be on github - any `git request-pull`works. Or even sending me a patch with `git format-patch`.
