### ISSUE TITLE
cannon needs fixing after new website design

### ISSUE THREAD

**Issue by bdliliedahl** [pirxpilot/liftie#92]
Fix below. Might be simpler using the selectors but I couldn't figure it out from the docs. 

`function parse(dom) {
  const liftStatus = {};

  select(dom, 'table.min-w-full.bg-white.mb-16 tbody').forEach((body) => {
    body.children.forEach(row => {
      const svg = row.children[0].children[0]
      const label = row.children[1].children[0].children[0].data
      const l = trim(label)
      const s = svg.attribs['aria-label']
      liftStatus[l] = coerce(split(s, ' ')[0])
    })
  })

  debug('Cannon Lift Status:', liftStatus);
  return liftStatus;
}
`

**Comment by pirxpilot** [comment]
Thanks.
Please review e47dd53 - see if any further changes are required.
PRs for other resorts (or the docs) welcomed.
